# Generated by Django 3.1.1 on 2020-09-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdbpost',
            name='image',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
