# Generated by Django 3.1.1 on 2020-09-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPost', '0002_createdbpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdbpost',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
