# Generated by Django 3.1.1 on 2020-09-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPost', '0007_remove_image_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='createdbpost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
