# Generated by Django 3.1.1 on 2020-09-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPost', '0008_auto_20200905_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='createImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='createdbpost',
            name='image',
        ),
    ]
