# Generated by Django 3.1.1 on 2020-09-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPost', '0009_auto_20200905_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createImg',
        ),
        migrations.AddField(
            model_name='createdbpost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
